columns:
- _id: object
- subscription_length: float64
- vehicle_age:  float64
- customer_age:  int64
- region_code:  object
- region_density: int64
- segment:  object
- model:  object
- fuel_type:  object
- max_torque: object
- max_power:  object
- engine_type:  object
- airbags:  int64
- is_esc:   object
- is_adjustable_steering: object
- is_tpms:  object
- is_parking_sensors: object
- is_parking_camera:  object
- rear_brakes_type:  object
- displacement:  int64
- cylinder:  int64
- transmission_type:  object
- steering_type:  object
- turning_radius:  float64
- length:  int64
- width:  int64
- gross_weight:  int64
- is_front_fog_lights: object
- is_rear_window_wiper:  object
- is_rear_window_washer:  object
- is_rear_window_defogger: object
- is_brake_assist:  object
- is_power_door_locks:  object
- is_central_locking:  object
- is_power_steering:  object
- is_driver_seat_height_adjustable:  object
- is_day_night_rear_view_mirror:  object
- is_ecw:  object
- is_speed_alert: object
- ncap_rating:  int64
- claim_status:  object


numerical_columns:
- subscription_length
- vehicle_age
- customer_age
- region_density
- airbags
- displacement
- cylinder
- turning_radius
- length
- width
- gross_weight
- ncap_rating

categorical_columns:
- region_code
- segment
- model
- fuel_type
- max_torque
- max_power
- engine_type
- is_esc
- is_adjustable_steering
- is_tpms
- is_parking_sensors
- is_parking_camera
- rear_brakes_type
- transmission_type
- steering_type
- is_front_fog_lights
- is_rear_window_wiper
- is_rear_window_washer
- is_rear_window_defogger
- is_brake_assist
- is_power_door_locks
- is_central_locking
- is_power_steering
- is_driver_seat_height_adjustable
- is_day_night_rear_view_mirror
- is_ecw
- is_speed_alert

drop_columns: _id

# for data transformation
num_features:
- subscription_length
- vehicle_age
- customer_age
- region_density
- airbags
- displacement
- cylinder
- turning_radius
- length
- width
- gross_weight
- ncap_rating
# mm_columns:
#   - claim_status